---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# gavir

<!-- badges: start -->
<!-- badges: end -->

This package is a hodge podge of helper functions that can be used at Gavi. It mainly has functions to help simplify repeat procedures, like functions to add Gavi colors to plots. 

## Installation

You can install the development version of gavir from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("joshualorin/gavir")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(gavir)
library(tidyverse)
## basic example code

wuenic %>%
 filter(iso3 == "AFG" & vaccine %in% c("dtp1", "dtp3")) %>%
 ggplot(aes(year, coverage, color = vaccine)) +
 geom_line() +
 scale_color_gavi()

```

